stages:
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: testing/java-hello:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: https://registry-infra.jaklingkoindonesia.co.id
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
