apiVersion: v1
kind: Service
metadata:
  namespace: testing-pipeline
  name: java-hello
  labels:
    app: java-hello
    service: java-hello
spec:
  selector:
    app: java-hello
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testing-pipeline
  name: java-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-hello
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: java-hello
        version: v1
    spec:
      containers:
        - name: java-hello
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - protocol: TCP
              containerPort: 8888
          env:
            - name: TZ
              value: "Asia/Jakarta"
          securityContext:
            privileged: true
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

